Repository freeserverproject/freeserver-wiki, pull requests merged in 2021-07, with the labels that each got.

#34 Update 運営一覧 “index”
  docs/admins/index.md
Labels: netlify-cms/draft

#36 Update 運営一覧 “Nakatai_0322”
  docs/admins/Nakatai_0322.md
Labels: netlify-cms/pending_publish

#29 Create ワールド一覧 “地上絵ワールド”
  docs/world/art-world.md
Labels: netlify-cms/pending_review

#33 Create 規約類 “how-to-apply-for-railway-construction”
  docs/terms/how-to-apply-for-railway-construction.md
Labels: netlify-cms/pending_publish

#38 Update 固定ページ “index”
  docs/index.md
Labels: netlify-cms/pending_publish

#39 Update 規約類 “how-to-apply-for-railway-construction”
  docs/terms/how-to-apply-for-railway-construction.md
Labels: netlify-cms/pending_publish

#40 Update 規約類 “how-to-apply-for-railway-construction”
  docs/terms/how-to-apply-for-railway-construction.md
Labels: netlify-cms/pending_publish

#41 Update 規約類 “how-to-apply-for-railway-construction”
  docs/terms/how-to-apply-for-railway-construction.md
Labels: netlify-cms/pending_publish

#42 Create 鉄道 “route-note-template”
  docs/trains/route-note-template.md
Labels: netlify-cms/pending_publish

#43 Update 規約類 “how-to-apply-for-railway-construction”
  docs/terms/how-to-apply-for-railway-construction.md
Labels: netlify-cms/pending_publish

#37 Create ワールド一覧 “index”
  docs/world/index.md
Labels: netlify-cms/pending_review

#45 Create ワールド一覧 “mobトラップ一覧”
  docs/world/mobトラップ一覧.md
Labels: netlify-cms/draft

#47 Update 規約類 “how-to-apply-for-railway-construction”
  docs/terms/how-to-apply-for-railway-construction.md
Labels: netlify-cms/pending_publish

#48 Update 固定ページ “index”
  docs/index.md
Labels: netlify-cms/draft

#49 Create イベント “運営ラジオ”
  docs/event/運営ラジオ.md
Labels: netlify-cms/draft
